apiVersion: 1

datasources:
  - name: CDC-Metrics
    uid: CDC-Metrics
    type: simpod-json-datasource
    access: proxy
    url: http://api:3001
    isDefault: true
    version: 1
    editable: true